"use client";
import { useState } from "react";
type Section = "painel" | "historia" | "membro" | "casos";
const assetBasePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const notices = [["17 SET 2026","CASO 001 ARQUIVADO","A documentação do Protocolo Delectus foi transferida para a biblioteca do membro."],["14 SET 2026","NÍVEL I CONFIRMADO","Áreas institucionais iniciais foram liberadas para consulta."],["—","NOVAS ATRIBUIÇÕES","Nenhuma investigação adicional foi atribuída à sua referência neste momento."]];
function Mark(){return <img className="brand-mark" src={`${assetBasePath}/brand/ordo-mognus-logo.png`} alt="Monograma Ordo Mognus"/>}
function Metric({title,value}:{title:string;value:string}){return <div className="metric"><p>{title}</p><strong>{value}</strong></div>}
export default function Home(){const [section,setSection]=useState<Section>("painel");const [caseOpen,setCaseOpen]=useState(false);const nav:[Section,string][]=[["painel","Painel"],["historia","História"],["membro","Membro"],["casos","Casos"]];return <main className="portal-shell"><header className="site-header"><button className="brand" onClick={()=>setSection("painel")}><Mark/><span>ORDO MOGNUS</span></button><nav>{nav.map(([id,label])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}>{label}</button>)}</nav><div className="member-chip"><span>REFERÊNCIA: IGNIS</span><strong>NÍVEL I</strong></div></header><section className="access-line"><span>SISTEMA INSTITUCIONAL</span><i/> <span>MEMBRO ATIVO</span><i/><span>ACESSO NÍVEL I</span></section>{section==="painel"&&<Dashboard onCases={()=>setSection("casos")}/>} {section==="historia"&&<History/>}{section==="membro"&&<Member/>}{section==="casos"&&<Cases openCase={()=>setCaseOpen(true)}/>} {caseOpen&&<CaseDialog onClose={()=>setCaseOpen(false)}/>}<footer>ORDO MOGNUS · REGISTRO INSTITUCIONAL · DOCUMENTAÇÃO INTERNA</footer></main>}
function Dashboard({onCases}:{onCases:()=>void}){return <section className="page dashboard"><div className="watermark"><Mark/></div><p className="eyebrow">PAINEL DO MEMBRO</p><h1>Bem-vindo, <em>IGNIS.</em></h1><p className="lead">Sua admissão foi registrada. A área abaixo reúne os materiais e comunicados autorizados para seu nível atual.</p><div className="metrics"><Metric title="STATUS" value="ATIVO"/><Metric title="NÍVEL DE ACESSO" value="I"/><Metric title="ADMISSÃO" value="17 SET 2026"/><Metric title="CASOS CONCLUÍDOS" value="01"/></div><section className="notice-section"><div className="section-heading"><p>AVISOS RECENTES</p><span>ARQUIVO DO MEMBRO</span></div>{notices.map(([date,title,copy])=><article className="notice" key={title}><time>{date}</time><div><h2>{title}</h2><p>{copy}</p></div></article>)}</section><button className="gold-button" onClick={onCases}>ACESSAR BIBLIOTECA DE CASOS <span>→</span></button></section>}
function History(){return <section className="page history"><p className="eyebrow">ARQUIVO INSTITUCIONAL</p><h1>História <em>parcial.</em></h1><p className="lead">Os trechos preservados indicam uma instituição formada para manter, comparar e isolar ocorrências que resistem a explicações ordinárias.</p><div className="timeline"><article><time>SÉCULO XIX</time><h2>FUNDAÇÃO DO ACERVO</h2><p>Os primeiros registros foram reunidos sob protocolos de classificação ainda preservados apenas parcialmente.</p></article><article className="restricted"><time>1908 — 1947</time><h2>DOCUMENTAÇÃO PARCIAL</h2><p>Referências a núcleos de observação e arquivos deslocados.</p><span>ACESSO RESTRITO — NÍVEL II</span></article><article><time>1987</time><h2>REORGANIZAÇÃO DE REGISTROS</h2><p>Materiais sem procedência foram incorporados a uma linha de investigação interna.</p></article><article className="restricted"><time>ATUALIDADE</time><h2>REGISTRO BLOQUEADO</h2><p>O conteúdo deste período requer autorização superior.</p><span>REGISTRO BLOQUEADO</span></article></div></section>}
function Member(){return <section className="page member"><div className="level-watermark">I</div><p className="eyebrow">FICHA INSTITUCIONAL</p><h1>Registro de <em>membro.</em></h1><div className="member-sheet"><div className="member-ident"><Mark/><div><p>REFERÊNCIA</p><h2>IGNIS</h2><span>MEMBRO ATIVO · NÍVEL I</span></div></div><dl><div><dt>ADMISSÃO</dt><dd>17 SET 2026</dd></div><div><dt>FUNÇÃO</dt><dd>OBSERVADOR</dd></div><div><dt>CASOS CONCLUÍDOS</dt><dd>01</dd></div><div><dt>PROTOCOLOS CONCLUÍDOS</dt><dd>01</dd></div><div><dt>ÁREAS AUTORIZADAS</dt><dd>PAINEL · HISTÓRIA · CASOS</dd></div><div><dt>ÁREAS RESTRITAS</dt><dd>NÍVEL II E SUPERIOR</dd></div></dl></div></section>}
function Cases({openCase}:{openCase:()=>void}){return <section className="page cases"><p className="eyebrow">BIBLIOTECA INSTITUCIONAL</p><h1>Casos em <em>arquivo.</em></h1><p className="lead">Investigações atribuídas, preservadas ou aguardando autorização.</p><article className="case-row complete"><div className="case-id">001</div><div><p>ARQUIVADO · ACESSO AUTORIZADO</p><h2>O ESPELHO NEGRO</h2><span>Protocolo Delectus · Concluído em 17 SET 2026</span></div><button onClick={openCase}>ABRIR ARQUIVO <b>→</b></button></article><article className="case-row"><div className="case-id">002</div><div><p>EM TRIAGEM</p><h2>DOCUMENTAÇÃO PENDENTE</h2><span>Atribuição ainda não liberada.</span></div><button disabled>AGUARDAR</button></article><article className="case-row"><div className="case-id">003</div><div><p>ACESSO NÃO AUTORIZADO</p><h2>REGISTRO RESTRITO</h2><span>Nível II necessário para consulta.</span></div><button disabled>BLOQUEADO</button></article></section>}
function CaseDialog({onClose}:{onClose:()=>void}){return <div className="modal"><section className="case-dialog"><button className="close" onClick={onClose}>×</button><p className="eyebrow">CASO 001 · ARQUIVO ENCERRADO</p><h2>O ESPELHO NEGRO</h2><p className="dialog-lead">A investigação foi concluída sob o Protocolo Delectus. O acervo permanece disponível para revisão.</p><div className="review-list">{["CRONOLOGIA","DOCUMENTOS","SESSÃO XI","SALA DE 1994","ESPELHO","CONCLUSÃO DA INVESTIGAÇÃO"].map(item=><button key={item}>{item}<span>→</span></button>)}</div><small>Os materiais completos serão conectados ao arquivo nesta fase posterior.</small></section></div>}
